[DEBUG] 2017-05-25 11:30:28,302 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 11:34:28,581 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 11:38:28,862 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 11:42:29,145 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 11:46:29,400 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 11:50:29,674 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 11:54:29,945 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 11:58:30,220 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 12:02:30,527 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[ERROR] 2017-05-25 12:02:30,817 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: [Errno 13] Permission denied: './mypaper.co.in/error-snapshots/2017-05-25 12:02:30.747446-127.0.0.1-b01.json'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 38, in make_error_snapshot
    with open(encode(snapshot_file_path), 'wb') as error_file:
IOError: [Errno 13] Permission denied: './mypaper.co.in/error-snapshots/2017-05-25 12:02:30.747446-127.0.0.1-b01.json'
[DEBUG] 2017-05-25 12:06:30,809 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 12:10:31,041 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 12:14:31,285 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 12:18:31,566 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 12:22:31,842 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 12:26:32,122 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 12:30:32,398 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 12:34:32,662 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 12:38:32,927 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 12:42:33,269 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 12:46:33,595 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 12:50:34,369 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 12:54:34,763 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 12:58:35,089 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 13:02:35,452 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[ERROR] 2017-05-25 13:02:35,935 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: [Errno 13] Permission denied: './mypaper.co.in/error-snapshots/2017-05-25 13:02:35.819982-127.0.0.1-626.json'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 38, in make_error_snapshot
    with open(encode(snapshot_file_path), 'wb') as error_file:
IOError: [Errno 13] Permission denied: './mypaper.co.in/error-snapshots/2017-05-25 13:02:35.819982-127.0.0.1-626.json'
[DEBUG] 2017-05-25 13:06:35,795 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 13:10:36,131 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 13:14:36,456 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 13:18:36,796 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 13:22:37,112 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 13:26:37,413 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 13:30:37,730 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 13:34:38,065 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 13:38:38,388 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 13:42:38,707 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 13:46:39,013 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 13:50:39,310 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 13:54:39,593 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 13:58:39,895 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 14:02:40,201 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[ERROR] 2017-05-25 14:02:40,506 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: [Errno 13] Permission denied: './mypaper.co.in/error-snapshots/2017-05-25 14:02:40.426462-127.0.0.1-cb6.json'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 38, in make_error_snapshot
    with open(encode(snapshot_file_path), 'wb') as error_file:
IOError: [Errno 13] Permission denied: './mypaper.co.in/error-snapshots/2017-05-25 14:02:40.426462-127.0.0.1-cb6.json'
[DEBUG] 2017-05-25 14:06:40,498 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 14:10:40,781 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 14:14:41,079 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 14:18:41,369 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 14:22:41,659 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 14:26:41,943 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 14:30:42,153 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 14:34:42,427 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 14:38:42,709 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 14:42:42,998 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 14:46:43,298 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 14:50:43,582 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 14:54:43,868 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 14:58:44,148 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 15:02:44,475 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[ERROR] 2017-05-25 15:02:44,787 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: [Errno 13] Permission denied: './mypaper.co.in/error-snapshots/2017-05-25 15:02:44.725996-127.0.0.1-bc3.json'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 38, in make_error_snapshot
    with open(encode(snapshot_file_path), 'wb') as error_file:
IOError: [Errno 13] Permission denied: './mypaper.co.in/error-snapshots/2017-05-25 15:02:44.725996-127.0.0.1-bc3.json'
[DEBUG] 2017-05-25 15:06:44,762 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 15:10:45,085 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 15:14:45,377 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 15:18:45,652 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 15:22:45,934 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 15:26:46,218 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 15:30:46,525 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 15:34:46,817 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 15:38:47,097 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 15:42:47,390 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 15:46:47,680 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 15:50:47,990 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 15:54:48,269 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 15:58:48,534 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 16:02:48,863 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[ERROR] 2017-05-25 16:02:49,198 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: [Errno 13] Permission denied: './mypaper.co.in/error-snapshots/2017-05-25 16:02:49.121216-127.0.0.1-be7.json'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 38, in make_error_snapshot
    with open(encode(snapshot_file_path), 'wb') as error_file:
IOError: [Errno 13] Permission denied: './mypaper.co.in/error-snapshots/2017-05-25 16:02:49.121216-127.0.0.1-be7.json'
[DEBUG] 2017-05-25 16:06:49,180 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 16:10:49,471 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 16:14:49,778 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 16:25:38,127 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[ERROR] 2017-05-25 16:27:54,140 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 69, in application
    response = frappe.website.render.render()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 65, in render
    data = render_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 117, in render_page
    return build(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 124, in build
    return build_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 137, in build_page
    context = get_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/context.py", line 15, in get_context
    context = get_page_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 35, in get_page_context
    page_context = make_page_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 44, in make_page_context
    context = resolve_route(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 18, in resolve_route
    context = get_page_context_from_template(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 60, in get_page_context_from_template
    app_path = frappe.get_app_path(app)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 695, in get_app_path
    return get_pymodule_path(app_name, *joins)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 710, in get_pymodule_path
    return os.path.join(os.path.dirname(get_module(scrub(modulename)).__file__), *joins)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named newapp
[ERROR] 2017-05-25 16:27:54,213 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-25 16:27:54.143648-203.122.45.98-f1b
[ERROR] 2017-05-25 16:27:55,230 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 69, in application
    response = frappe.website.render.render()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 65, in render
    data = render_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 117, in render_page
    return build(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 124, in build
    return build_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 137, in build_page
    context = get_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/context.py", line 15, in get_context
    context = get_page_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 35, in get_page_context
    page_context = make_page_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 44, in make_page_context
    context = resolve_route(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 18, in resolve_route
    context = get_page_context_from_template(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 60, in get_page_context_from_template
    app_path = frappe.get_app_path(app)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 695, in get_app_path
    return get_pymodule_path(app_name, *joins)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 710, in get_pymodule_path
    return os.path.join(os.path.dirname(get_module(scrub(modulename)).__file__), *joins)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named newapp
[ERROR] 2017-05-25 16:27:55,237 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-25 16:27:55.231327-203.122.45.98-7db
[ERROR] 2017-05-25 16:27:55,979 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 69, in application
    response = frappe.website.render.render()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 65, in render
    data = render_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 117, in render_page
    return build(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 124, in build
    return build_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 137, in build_page
    context = get_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/context.py", line 15, in get_context
    context = get_page_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 35, in get_page_context
    page_context = make_page_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 44, in make_page_context
    context = resolve_route(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 18, in resolve_route
    context = get_page_context_from_template(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 60, in get_page_context_from_template
    app_path = frappe.get_app_path(app)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 695, in get_app_path
    return get_pymodule_path(app_name, *joins)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 710, in get_pymodule_path
    return os.path.join(os.path.dirname(get_module(scrub(modulename)).__file__), *joins)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named newapp
[ERROR] 2017-05-25 16:27:55,986 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-25 16:27:55.980028-203.122.45.98-4c0
[ERROR] 2017-05-25 16:28:01,449 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 69, in application
    response = frappe.website.render.render()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 65, in render
    data = render_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 117, in render_page
    return build(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 124, in build
    return build_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 137, in build_page
    context = get_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/context.py", line 15, in get_context
    context = get_page_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 35, in get_page_context
    page_context = make_page_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 44, in make_page_context
    context = resolve_route(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 18, in resolve_route
    context = get_page_context_from_template(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 60, in get_page_context_from_template
    app_path = frappe.get_app_path(app)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 695, in get_app_path
    return get_pymodule_path(app_name, *joins)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 710, in get_pymodule_path
    return os.path.join(os.path.dirname(get_module(scrub(modulename)).__file__), *joins)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named newapp
[ERROR] 2017-05-25 16:28:01,453 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-25 16:28:01.449501-203.122.45.98-d13
[ERROR] 2017-05-25 16:28:24,704 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Form Dict: {
 "cmd": "frappe.sessions.clear"
}
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 52, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 907, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/sessions.py", line 28, in clear
    clear_global_cache()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/sessions.py", line 56, in clear_global_cache
    frappe.setup_module_map()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 840, in setup_module_map
    for module in get_module_list(app):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 714, in get_module_list
    return get_file_items(os.path.join(os.path.dirname(get_module(app_name).__file__), "modules.txt"))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named newapp
[ERROR] 2017-05-25 16:28:24,709 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-25 16:28:24.704862-203.122.45.98-111
[ERROR] 2017-05-25 16:28:30,990 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 52, in application
    init_request(request)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 103, in init_request
    frappe.init(site=site, sites_path=_sites_path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 155, in init
    setup_module_map()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 840, in setup_module_map
    for module in get_module_list(app):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 714, in get_module_list
    return get_file_items(os.path.join(os.path.dirname(get_module(app_name).__file__), "modules.txt"))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named newapp
[ERROR] 2017-05-25 16:28:30,993 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-25 16:28:30.990879-127.0.0.1-772
[ERROR] 2017-05-25 16:28:58,538 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 52, in application
    init_request(request)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 103, in init_request
    frappe.init(site=site, sites_path=_sites_path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 155, in init
    setup_module_map()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 840, in setup_module_map
    for module in get_module_list(app):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 714, in get_module_list
    return get_file_items(os.path.join(os.path.dirname(get_module(app_name).__file__), "modules.txt"))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named newapp
[ERROR] 2017-05-25 16:28:58,541 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-25 16:28:58.539053-127.0.0.1-e9f
[ERROR] 2017-05-25 16:29:00,994 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 52, in application
    init_request(request)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 103, in init_request
    frappe.init(site=site, sites_path=_sites_path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 155, in init
    setup_module_map()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 840, in setup_module_map
    for module in get_module_list(app):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 714, in get_module_list
    return get_file_items(os.path.join(os.path.dirname(get_module(app_name).__file__), "modules.txt"))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named newapp
[ERROR] 2017-05-25 16:29:00,999 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-25 16:29:00.995554-127.0.0.1-7fa
[ERROR] 2017-05-25 16:29:31,039 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 52, in application
    init_request(request)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 103, in init_request
    frappe.init(site=site, sites_path=_sites_path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 155, in init
    setup_module_map()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 840, in setup_module_map
    for module in get_module_list(app):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 714, in get_module_list
    return get_file_items(os.path.join(os.path.dirname(get_module(app_name).__file__), "modules.txt"))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named newapp
[ERROR] 2017-05-25 16:29:31,043 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-25 16:29:31.039516-127.0.0.1-f2f
[ERROR] 2017-05-25 16:29:33,062 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 52, in application
    init_request(request)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 103, in init_request
    frappe.init(site=site, sites_path=_sites_path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 155, in init
    setup_module_map()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 840, in setup_module_map
    for module in get_module_list(app):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 714, in get_module_list
    return get_file_items(os.path.join(os.path.dirname(get_module(app_name).__file__), "modules.txt"))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named newapp
[ERROR] 2017-05-25 16:29:33,065 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-25 16:29:33.062644-127.0.0.1-870
[ERROR] 2017-05-25 16:29:33,440 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 52, in application
    init_request(request)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 103, in init_request
    frappe.init(site=site, sites_path=_sites_path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 155, in init
    setup_module_map()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 840, in setup_module_map
    for module in get_module_list(app):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 714, in get_module_list
    return get_file_items(os.path.join(os.path.dirname(get_module(app_name).__file__), "modules.txt"))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named newapp
[ERROR] 2017-05-25 16:29:33,442 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-25 16:29:33.440367-127.0.0.1-91e
[DEBUG] 2017-05-25 16:29:38,421 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[ERROR] 2017-05-25 16:29:42,157 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 69, in application
    response = frappe.website.render.render()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 22, in render
    path = resolve_path(path or frappe.local.request.path.strip('/ '))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 161, in resolve_path
    path = get_home_page()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/utils.py", line 70, in get_home_page
    return frappe.cache().hget("home_page", frappe.session.user, _get_home_page)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 171, in hget
    value = generator()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/utils.py", line 46, in _get_home_page
    get_website_user_home_page = frappe.get_hooks('get_website_user_home_page')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 800, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", load_app_hooks))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 70, in get_value
    val = generator()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 781, in load_app_hooks
    app_hooks = get_module(app + ".hooks")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named newapp.hooks
[ERROR] 2017-05-25 16:29:42,161 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-25 16:29:42.157834-203.122.45.98-5c7
[ERROR] 2017-05-25 16:29:42,262 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 69, in application
    response = frappe.website.render.render()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 65, in render
    data = render_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 117, in render_page
    return build(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 124, in build
    return build_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 137, in build_page
    context = get_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/context.py", line 15, in get_context
    context = get_page_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 35, in get_page_context
    page_context = make_page_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 44, in make_page_context
    context = resolve_route(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 18, in resolve_route
    context = get_page_context_from_template(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 60, in get_page_context_from_template
    app_path = frappe.get_app_path(app)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 695, in get_app_path
    return get_pymodule_path(app_name, *joins)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 710, in get_pymodule_path
    return os.path.join(os.path.dirname(get_module(scrub(modulename)).__file__), *joins)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named newapp
[ERROR] 2017-05-25 16:29:42,270 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-25 16:29:42.263771-203.122.45.98-580
[ERROR] 2017-05-25 16:30:08,520 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 69, in application
    response = frappe.website.render.render()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 22, in render
    path = resolve_path(path or frappe.local.request.path.strip('/ '))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 161, in resolve_path
    path = get_home_page()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/utils.py", line 70, in get_home_page
    return frappe.cache().hget("home_page", frappe.session.user, _get_home_page)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 171, in hget
    value = generator()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/utils.py", line 46, in _get_home_page
    get_website_user_home_page = frappe.get_hooks('get_website_user_home_page')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 800, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", load_app_hooks))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 70, in get_value
    val = generator()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 781, in load_app_hooks
    app_hooks = get_module(app + ".hooks")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named newapp.hooks
[ERROR] 2017-05-25 16:30:08,526 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-25 16:30:08.521454-203.122.45.98-fa9
[ERROR] 2017-05-25 16:30:08,703 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 69, in application
    response = frappe.website.render.render()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 22, in render
    path = resolve_path(path or frappe.local.request.path.strip('/ '))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 161, in resolve_path
    path = get_home_page()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/utils.py", line 70, in get_home_page
    return frappe.cache().hget("home_page", frappe.session.user, _get_home_page)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 171, in hget
    value = generator()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/utils.py", line 46, in _get_home_page
    get_website_user_home_page = frappe.get_hooks('get_website_user_home_page')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 800, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", load_app_hooks))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 70, in get_value
    val = generator()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 781, in load_app_hooks
    app_hooks = get_module(app + ".hooks")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named newapp.hooks
[ERROR] 2017-05-25 16:30:08,709 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-25 16:30:08.703815-203.122.45.98-ea0
[ERROR] 2017-05-25 16:30:08,886 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 69, in application
    response = frappe.website.render.render()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 65, in render
    data = render_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 117, in render_page
    return build(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 124, in build
    return build_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 137, in build_page
    context = get_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/context.py", line 15, in get_context
    context = get_page_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 35, in get_page_context
    page_context = make_page_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 44, in make_page_context
    context = resolve_route(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 18, in resolve_route
    context = get_page_context_from_template(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 60, in get_page_context_from_template
    app_path = frappe.get_app_path(app)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 695, in get_app_path
    return get_pymodule_path(app_name, *joins)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 710, in get_pymodule_path
    return os.path.join(os.path.dirname(get_module(scrub(modulename)).__file__), *joins)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named newapp
[ERROR] 2017-05-25 16:30:08,895 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-25 16:30:08.886974-203.122.45.98-063
[ERROR] 2017-05-25 16:30:09,194 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 69, in application
    response = frappe.website.render.render()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 22, in render
    path = resolve_path(path or frappe.local.request.path.strip('/ '))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 161, in resolve_path
    path = get_home_page()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/utils.py", line 70, in get_home_page
    return frappe.cache().hget("home_page", frappe.session.user, _get_home_page)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 171, in hget
    value = generator()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/utils.py", line 46, in _get_home_page
    get_website_user_home_page = frappe.get_hooks('get_website_user_home_page')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 800, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", load_app_hooks))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 70, in get_value
    val = generator()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 781, in load_app_hooks
    app_hooks = get_module(app + ".hooks")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named newapp.hooks
[ERROR] 2017-05-25 16:30:09,198 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-25 16:30:09.194758-203.122.45.98-d73
[ERROR] 2017-05-25 16:30:09,343 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 69, in application
    response = frappe.website.render.render()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 65, in render
    data = render_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 117, in render_page
    return build(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 124, in build
    return build_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 137, in build_page
    context = get_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/context.py", line 15, in get_context
    context = get_page_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 35, in get_page_context
    page_context = make_page_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 44, in make_page_context
    context = resolve_route(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 18, in resolve_route
    context = get_page_context_from_template(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 60, in get_page_context_from_template
    app_path = frappe.get_app_path(app)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 695, in get_app_path
    return get_pymodule_path(app_name, *joins)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 710, in get_pymodule_path
    return os.path.join(os.path.dirname(get_module(scrub(modulename)).__file__), *joins)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named newapp
[ERROR] 2017-05-25 16:30:09,347 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-25 16:30:09.343418-203.122.45.98-6cd
[ERROR] 2017-05-25 16:30:09,656 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 69, in application
    response = frappe.website.render.render()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 22, in render
    path = resolve_path(path or frappe.local.request.path.strip('/ '))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 161, in resolve_path
    path = get_home_page()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/utils.py", line 70, in get_home_page
    return frappe.cache().hget("home_page", frappe.session.user, _get_home_page)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 171, in hget
    value = generator()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/utils.py", line 46, in _get_home_page
    get_website_user_home_page = frappe.get_hooks('get_website_user_home_page')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 800, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", load_app_hooks))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 70, in get_value
    val = generator()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 781, in load_app_hooks
    app_hooks = get_module(app + ".hooks")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named newapp.hooks
[ERROR] 2017-05-25 16:30:09,663 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-25 16:30:09.656782-203.122.45.98-c92
[ERROR] 2017-05-25 16:30:09,791 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 69, in application
    response = frappe.website.render.render()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 65, in render
    data = render_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 117, in render_page
    return build(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 124, in build
    return build_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 137, in build_page
    context = get_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/context.py", line 15, in get_context
    context = get_page_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 35, in get_page_context
    page_context = make_page_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 44, in make_page_context
    context = resolve_route(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 18, in resolve_route
    context = get_page_context_from_template(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 60, in get_page_context_from_template
    app_path = frappe.get_app_path(app)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 695, in get_app_path
    return get_pymodule_path(app_name, *joins)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 710, in get_pymodule_path
    return os.path.join(os.path.dirname(get_module(scrub(modulename)).__file__), *joins)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named newapp
[ERROR] 2017-05-25 16:30:09,798 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-25 16:30:09.791830-203.122.45.98-872
[ERROR] 2017-05-25 16:30:31,193 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Form Dict: {
 "cmd": "frappe.desk.notifications.get_notifications"
}
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 35, in execute_cmd
    for hook in frappe.get_hooks("override_whitelisted_methods", {}).get(cmd, []):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 800, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", load_app_hooks))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 70, in get_value
    val = generator()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 781, in load_app_hooks
    app_hooks = get_module(app + ".hooks")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named newapp.hooks
[ERROR] 2017-05-25 16:30:31,197 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-25 16:30:31.193939-203.122.45.98-e88
[ERROR] 2017-05-25 16:31:31,089 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Form Dict: {
 "cmd": "frappe.desk.notifications.get_notifications"
}
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 35, in execute_cmd
    for hook in frappe.get_hooks("override_whitelisted_methods", {}).get(cmd, []):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 800, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", load_app_hooks))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 70, in get_value
    val = generator()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 781, in load_app_hooks
    app_hooks = get_module(app + ".hooks")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named newapp.hooks
[ERROR] 2017-05-25 16:31:31,093 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-25 16:31:31.090350-203.122.45.98-3bf
[ERROR] 2017-05-25 16:32:12,301 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 69, in application
    response = frappe.website.render.render()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 22, in render
    path = resolve_path(path or frappe.local.request.path.strip('/ '))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 161, in resolve_path
    path = get_home_page()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/utils.py", line 70, in get_home_page
    return frappe.cache().hget("home_page", frappe.session.user, _get_home_page)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 171, in hget
    value = generator()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/utils.py", line 46, in _get_home_page
    get_website_user_home_page = frappe.get_hooks('get_website_user_home_page')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 800, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", load_app_hooks))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 70, in get_value
    val = generator()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 781, in load_app_hooks
    app_hooks = get_module(app + ".hooks")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named newapp.hooks
[ERROR] 2017-05-25 16:32:12,306 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-25 16:32:12.302098-203.122.45.98-9cf
[ERROR] 2017-05-25 16:32:12,507 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 69, in application
    response = frappe.website.render.render()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 65, in render
    data = render_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 117, in render_page
    return build(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 124, in build
    return build_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 137, in build_page
    context = get_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/context.py", line 15, in get_context
    context = get_page_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 35, in get_page_context
    page_context = make_page_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 44, in make_page_context
    context = resolve_route(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 18, in resolve_route
    context = get_page_context_from_template(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 60, in get_page_context_from_template
    app_path = frappe.get_app_path(app)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 695, in get_app_path
    return get_pymodule_path(app_name, *joins)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 710, in get_pymodule_path
    return os.path.join(os.path.dirname(get_module(scrub(modulename)).__file__), *joins)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named newapp
[ERROR] 2017-05-25 16:32:12,511 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-25 16:32:12.507603-203.122.45.98-120
[ERROR] 2017-05-25 16:32:12,866 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 69, in application
    response = frappe.website.render.render()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 22, in render
    path = resolve_path(path or frappe.local.request.path.strip('/ '))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 161, in resolve_path
    path = get_home_page()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/utils.py", line 70, in get_home_page
    return frappe.cache().hget("home_page", frappe.session.user, _get_home_page)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 171, in hget
    value = generator()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/utils.py", line 46, in _get_home_page
    get_website_user_home_page = frappe.get_hooks('get_website_user_home_page')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 800, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", load_app_hooks))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 70, in get_value
    val = generator()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 781, in load_app_hooks
    app_hooks = get_module(app + ".hooks")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named newapp.hooks
[ERROR] 2017-05-25 16:32:12,870 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-25 16:32:12.866478-203.122.45.98-e4b
[ERROR] 2017-05-25 16:32:13,032 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 69, in application
    response = frappe.website.render.render()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 65, in render
    data = render_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 117, in render_page
    return build(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 124, in build
    return build_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 137, in build_page
    context = get_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/context.py", line 15, in get_context
    context = get_page_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 35, in get_page_context
    page_context = make_page_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 44, in make_page_context
    context = resolve_route(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 18, in resolve_route
    context = get_page_context_from_template(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 60, in get_page_context_from_template
    app_path = frappe.get_app_path(app)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 695, in get_app_path
    return get_pymodule_path(app_name, *joins)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 710, in get_pymodule_path
    return os.path.join(os.path.dirname(get_module(scrub(modulename)).__file__), *joins)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named newapp
[ERROR] 2017-05-25 16:32:13,038 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-25 16:32:13.032837-203.122.45.98-0c5
[DEBUG] 2017-05-25 16:33:38,737 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[ERROR] 2017-05-25 16:34:06,186 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Form Dict: {
 "cmd": "frappe.desk.notifications.get_notifications"
}
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 21, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 35, in execute_cmd
    for hook in frappe.get_hooks("override_whitelisted_methods", {}).get(cmd, []):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 800, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", load_app_hooks))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 70, in get_value
    val = generator()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 781, in load_app_hooks
    app_hooks = get_module(app + ".hooks")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named newapp.hooks
[ERROR] 2017-05-25 16:34:06,190 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-25 16:34:06.186865-203.122.45.98-eba
[DEBUG] 2017-05-25 16:41:12,667 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 16:45:12,966 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 16:49:13,276 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 16:53:13,581 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 16:57:13,889 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 17:01:14,223 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[ERROR] 2017-05-25 17:01:14,839 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: [Errno 13] Permission denied: './mypaper.co.in/error-snapshots/2017-05-25 17:01:14.706698-127.0.0.1-793.json'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 38, in make_error_snapshot
    with open(encode(snapshot_file_path), 'wb') as error_file:
IOError: [Errno 13] Permission denied: './mypaper.co.in/error-snapshots/2017-05-25 17:01:14.706698-127.0.0.1-793.json'
[DEBUG] 2017-05-25 17:05:14,565 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 17:09:14,859 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 17:13:15,144 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 17:17:15,461 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 17:21:15,758 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 17:25:16,058 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 17:29:16,356 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 17:33:16,631 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 17:37:16,933 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 17:41:17,222 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 17:45:17,505 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 17:49:17,810 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 17:53:18,099 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 17:57:18,382 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 18:01:18,705 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[ERROR] 2017-05-25 18:01:19,029 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: [Errno 13] Permission denied: './mypaper.co.in/error-snapshots/2017-05-25 18:01:18.944537-127.0.0.1-e8a.json'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 38, in make_error_snapshot
    with open(encode(snapshot_file_path), 'wb') as error_file:
IOError: [Errno 13] Permission denied: './mypaper.co.in/error-snapshots/2017-05-25 18:01:18.944537-127.0.0.1-e8a.json'
[DEBUG] 2017-05-25 18:05:18,994 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 18:09:19,288 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 18:13:19,573 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 18:17:19,856 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 18:21:20,165 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 18:25:20,454 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 18:29:20,723 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 18:33:21,050 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 18:37:21,329 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 18:41:21,602 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 18:45:21,890 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 18:49:22,185 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 18:53:22,507 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 18:57:22,777 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 19:01:23,105 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[ERROR] 2017-05-25 19:01:23,763 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: [Errno 13] Permission denied: './mypaper.co.in/error-snapshots/2017-05-25 19:01:23.644010-127.0.0.1-bcf.json'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 38, in make_error_snapshot
    with open(encode(snapshot_file_path), 'wb') as error_file:
IOError: [Errno 13] Permission denied: './mypaper.co.in/error-snapshots/2017-05-25 19:01:23.644010-127.0.0.1-bcf.json'
[DEBUG] 2017-05-25 19:05:23,370 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 19:09:23,662 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 19:13:23,949 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 19:17:24,226 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 19:21:24,498 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 19:25:24,793 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 19:29:25,058 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 19:33:25,342 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 19:37:25,612 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 19:41:25,870 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 19:45:26,126 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 19:49:26,398 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 19:53:26,650 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 19:57:26,912 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 20:01:27,204 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[ERROR] 2017-05-25 20:01:27,665 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: [Errno 13] Permission denied: './mypaper.co.in/error-snapshots/2017-05-25 20:01:27.622092-127.0.0.1-544.json'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 38, in make_error_snapshot
    with open(encode(snapshot_file_path), 'wb') as error_file:
IOError: [Errno 13] Permission denied: './mypaper.co.in/error-snapshots/2017-05-25 20:01:27.622092-127.0.0.1-544.json'
[DEBUG] 2017-05-25 20:05:27,481 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 20:09:27,766 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 20:13:28,045 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 20:17:28,314 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 20:21:28,598 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 20:25:28,854 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 20:29:29,141 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 20:33:29,426 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 20:37:29,714 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 20:41:29,994 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 20:45:30,278 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 20:49:30,517 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 20:53:30,797 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 20:57:31,087 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 21:01:31,385 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[ERROR] 2017-05-25 21:01:31,634 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: [Errno 13] Permission denied: './mypaper.co.in/error-snapshots/2017-05-25 21:01:31.533313-127.0.0.1-486.json'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 38, in make_error_snapshot
    with open(encode(snapshot_file_path), 'wb') as error_file:
IOError: [Errno 13] Permission denied: './mypaper.co.in/error-snapshots/2017-05-25 21:01:31.533313-127.0.0.1-486.json'
[DEBUG] 2017-05-25 21:05:31,673 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 21:09:31,954 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 21:13:32,243 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 21:17:32,518 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 21:21:32,798 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 21:25:33,125 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 21:29:33,417 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 21:33:33,706 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 21:37:33,990 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 21:41:34,262 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 21:45:34,546 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 21:49:34,819 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 21:53:35,114 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 21:57:35,385 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 22:01:35,686 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[ERROR] 2017-05-25 22:01:35,934 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: [Errno 13] Permission denied: './mypaper.co.in/error-snapshots/2017-05-25 22:01:35.836060-127.0.0.1-fdb.json'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 38, in make_error_snapshot
    with open(encode(snapshot_file_path), 'wb') as error_file:
IOError: [Errno 13] Permission denied: './mypaper.co.in/error-snapshots/2017-05-25 22:01:35.836060-127.0.0.1-fdb.json'
[DEBUG] 2017-05-25 22:05:35,937 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 22:09:36,209 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 22:13:36,457 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 22:17:36,738 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 22:21:37,013 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 22:25:37,296 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 22:29:37,570 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 22:33:37,858 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 22:37:38,120 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 22:41:38,381 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 22:45:38,629 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 22:49:38,897 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 22:53:39,205 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 22:57:39,489 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 23:01:39,797 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[ERROR] 2017-05-25 23:01:40,003 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
Could not take error snapshot: [Errno 13] Permission denied: './mypaper.co.in/error-snapshots/2017-05-25 23:01:39.932013-127.0.0.1-8f0.json'
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py", line 38, in make_error_snapshot
    with open(encode(snapshot_file_path), 'wb') as error_file:
IOError: [Errno 13] Permission denied: './mypaper.co.in/error-snapshots/2017-05-25 23:01:39.932013-127.0.0.1-8f0.json'
[DEBUG] 2017-05-25 23:05:40,066 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[ERROR] 2017-05-25 23:08:32,302 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 69, in application
    response = frappe.website.render.render()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 65, in render
    data = render_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 117, in render_page
    return build(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 124, in build
    return build_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 137, in build_page
    context = get_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/context.py", line 15, in get_context
    context = get_page_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 35, in get_page_context
    page_context = make_page_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 44, in make_page_context
    context = resolve_route(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 18, in resolve_route
    context = get_page_context_from_template(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 71, in get_page_context_from_template
    return get_page_info(option, app, app_path=app_path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 203, in get_page_info
    setup_source(page_info)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 214, in setup_source
    jenv = frappe.get_jenv()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/jinja.py", line 14, in get_jenv
    set_filters(jenv)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/jinja.py", line 179, in set_filters
    for jenv_filter in (frappe.get_hooks(app_name=app).jenv_filter or []):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 798, in get_hooks
    hooks = _dict(load_app_hooks(app_name))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 781, in load_app_hooks
    app_hooks = get_module(app + ".hooks")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/frappe/frappe-bench/apps/newapp/newapp/hooks.py", line 86
    "Payment Entry": {
                  ^
SyntaxError: invalid syntax
[ERROR] 2017-05-25 23:08:32,373 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-25 23:08:32.303171-27.4.204.87-dcd
[ERROR] 2017-05-25 23:08:33,068 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 69, in application
    response = frappe.website.render.render()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 45, in render
    data = render_page('404')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 117, in render_page
    return build(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 124, in build
    return build_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 137, in build_page
    context = get_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/context.py", line 15, in get_context
    context = get_page_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 35, in get_page_context
    page_context = make_page_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 44, in make_page_context
    context = resolve_route(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 18, in resolve_route
    context = get_page_context_from_template(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 71, in get_page_context_from_template
    return get_page_info(option, app, app_path=app_path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 203, in get_page_info
    setup_source(page_info)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 214, in setup_source
    jenv = frappe.get_jenv()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/jinja.py", line 14, in get_jenv
    set_filters(jenv)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/jinja.py", line 179, in set_filters
    for jenv_filter in (frappe.get_hooks(app_name=app).jenv_filter or []):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 798, in get_hooks
    hooks = _dict(load_app_hooks(app_name))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 781, in load_app_hooks
    app_hooks = get_module(app + ".hooks")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/frappe/frappe-bench/apps/newapp/newapp/hooks.py", line 86
    "Payment Entry": {
                  ^
SyntaxError: invalid syntax
[ERROR] 2017-05-25 23:08:33,072 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-25 23:08:33.068488-27.4.204.87-6ec
[ERROR] 2017-05-25 23:08:35,415 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 69, in application
    response = frappe.website.render.render()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 65, in render
    data = render_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 117, in render_page
    return build(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 124, in build
    return build_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 137, in build_page
    context = get_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/context.py", line 15, in get_context
    context = get_page_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 35, in get_page_context
    page_context = make_page_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 44, in make_page_context
    context = resolve_route(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 18, in resolve_route
    context = get_page_context_from_template(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 71, in get_page_context_from_template
    return get_page_info(option, app, app_path=app_path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 203, in get_page_info
    setup_source(page_info)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 214, in setup_source
    jenv = frappe.get_jenv()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/jinja.py", line 14, in get_jenv
    set_filters(jenv)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/jinja.py", line 179, in set_filters
    for jenv_filter in (frappe.get_hooks(app_name=app).jenv_filter or []):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 798, in get_hooks
    hooks = _dict(load_app_hooks(app_name))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 781, in load_app_hooks
    app_hooks = get_module(app + ".hooks")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/frappe/frappe-bench/apps/newapp/newapp/hooks.py", line 86
    "Payment Entry": {
                  ^
SyntaxError: invalid syntax
[ERROR] 2017-05-25 23:08:35,420 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-25 23:08:35.415455-27.4.204.87-591
[DEBUG] 2017-05-25 23:09:40,333 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 23:13:40,613 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 23:17:40,893 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 23:21:41,170 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 23:25:41,443 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 23:29:41,722 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[DEBUG] 2017-05-25 23:33:41,966 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[ERROR] 2017-05-25 23:36:32,401 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 69, in application
    response = frappe.website.render.render()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 65, in render
    data = render_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 117, in render_page
    return build(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 124, in build
    return build_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 137, in build_page
    context = get_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/context.py", line 15, in get_context
    context = get_page_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 35, in get_page_context
    page_context = make_page_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 44, in make_page_context
    context = resolve_route(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 18, in resolve_route
    context = get_page_context_from_template(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 71, in get_page_context_from_template
    return get_page_info(option, app, app_path=app_path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 203, in get_page_info
    setup_source(page_info)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 214, in setup_source
    jenv = frappe.get_jenv()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/jinja.py", line 14, in get_jenv
    set_filters(jenv)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/jinja.py", line 179, in set_filters
    for jenv_filter in (frappe.get_hooks(app_name=app).jenv_filter or []):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 798, in get_hooks
    hooks = _dict(load_app_hooks(app_name))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 781, in load_app_hooks
    app_hooks = get_module(app + ".hooks")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/frappe/frappe-bench/apps/newapp/newapp/hooks.py", line 86
    "Payment Entry": {
                  ^
SyntaxError: invalid syntax
[ERROR] 2017-05-25 23:36:32,407 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-25 23:36:32.402190-47.30.78.112-63f
[ERROR] 2017-05-25 23:36:35,422 | /home/frappe/frappe-bench/apps/frappe/frappe/app.py:
Site: mypaper.co.in
Request Error
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 69, in application
    response = frappe.website.render.render()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 27, in render
    data = render_page('404')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 117, in render_page
    return build(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 124, in build
    return build_page(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/render.py", line 137, in build_page
    context = get_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/context.py", line 15, in get_context
    context = get_page_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 35, in get_page_context
    page_context = make_page_context(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 44, in make_page_context
    context = resolve_route(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 18, in resolve_route
    context = get_page_context_from_template(path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 71, in get_page_context_from_template
    return get_page_info(option, app, app_path=app_path)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 203, in get_page_info
    setup_source(page_info)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/router.py", line 214, in setup_source
    jenv = frappe.get_jenv()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/jinja.py", line 14, in get_jenv
    set_filters(jenv)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/jinja.py", line 179, in set_filters
    for jenv_filter in (frappe.get_hooks(app_name=app).jenv_filter or []):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 798, in get_hooks
    hooks = _dict(load_app_hooks(app_name))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 781, in load_app_hooks
    app_hooks = get_module(app + ".hooks")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 672, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/frappe/frappe-bench/apps/newapp/newapp/hooks.py", line 86
    "Payment Entry": {
                  ^
SyntaxError: invalid syntax
[ERROR] 2017-05-25 23:36:35,427 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-25 23:36:35.423259-47.30.78.112-63c
[ERROR] 2017-05-25 23:36:36,371 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-25 23:36:36.366353-47.30.78.112-ea8
[DEBUG] 2017-05-25 23:37:42,238 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py:
Site: mypaper.co.in
Queued events for site mypaper.co.in
[ERROR] 2017-05-25 23:38:01,196 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-25 23:38:01.189074-47.30.78.112-188
[ERROR] 2017-05-25 23:38:03,471 | /home/frappe/frappe-bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2017-05-25 23:38:03.466694-47.30.78.112-cf6
